import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { SYSTEM_PLAYBOOKS, ASSET_BLOCKS, type AssetBlockKind } from "./playbook-presets";

// Playbooks tables aren't in the autogenerated types yet; cast through the
// untyped client surface. RLS still enforces org-scoped access.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type SB = any;

const orgScoped = z.object({ organizationId: z.string().uuid() });

async function assertMember(supabase: SB, userId: string, organizationId: string) {
  const { data, error } = await supabase
    .from("organization_members")
    .select("id")
    .eq("user_id", userId)
    .eq("organization_id", organizationId)
    .maybeSingle();
  if (error) throw error;
  if (!data) throw new Error("Not a member of this organization");
}

export const listPlaybooks = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((i) => orgScoped.parse(i))
  .handler(async ({ data, context }) => {
    const supabase = context.supabase as SB;
    await assertMember(supabase, context.userId, data.organizationId);
    const { data: rows, error } = await supabase
      .from("playbooks")
      .select("*")
      .eq("organization_id", data.organizationId)
      .order("created_at", { ascending: false });
    if (error) throw error;
    return { playbooks: rows ?? [], assetCatalog: ASSET_BLOCKS };
  });

export const seedSystemPlaybooks = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((i) => orgScoped.parse(i))
  .handler(async ({ data, context }) => {
    const supabase = context.supabase as SB;
    await assertMember(supabase, context.userId, data.organizationId);
    const existing = await supabase
      .from("playbooks")
      .select("name")
      .eq("organization_id", data.organizationId)
      .eq("is_system", true);
    const existingNames = new Set((existing.data ?? []).map((r: { name: string }) => r.name));
    const toInsert = SYSTEM_PLAYBOOKS.filter((p) => !existingNames.has(p.name)).map((p) => ({
      organization_id: data.organizationId,
      name: p.name,
      description: p.description,
      target_intent: p.target_intent,
      asset_blocks: p.blocks.map((b) => ({ kind: b, weight: ASSET_BLOCKS[b].weight })),
      scoring_weights: { intent_match: 1.0, freshness: 0.5 },
      is_system: true,
      created_by: context.userId,
    }));
    if (toInsert.length === 0) return { inserted: 0 };
    const { error } = await supabase.from("playbooks").insert(toInsert);
    if (error) throw error;
    return { inserted: toInsert.length };
  });

export const createPlaybook = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((i) =>
    orgScoped
      .extend({
        name: z.string().min(2).max(120),
        description: z.string().max(1000).optional(),
        targetIntent: z.string().optional(),
        blocks: z.array(z.string()).min(1).max(20),
      })
      .parse(i),
  )
  .handler(async ({ data, context }) => {
    const supabase = context.supabase as SB;
    await assertMember(supabase, context.userId, data.organizationId);
    const blocks = data.blocks.map((k) => ({
      kind: k,
      weight: ASSET_BLOCKS[k as AssetBlockKind]?.weight ?? 5,
    }));
    const { data: row, error } = await supabase
      .from("playbooks")
      .insert({
        organization_id: data.organizationId,
        name: data.name,
        description: data.description ?? null,
        target_intent: data.targetIntent ?? null,
        asset_blocks: blocks,
        scoring_weights: {},
        is_system: false,
        created_by: context.userId,
      })
      .select()
      .single();
    if (error) throw error;
    return { playbook: row };
  });

export const applyPlaybook = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((i) =>
    orgScoped
      .extend({
        playbookId: z.string().uuid(),
        postIds: z.array(z.string().uuid()).min(1).max(50),
        siteId: z.string().uuid(),
      })
      .parse(i),
  )
  .handler(async ({ data, context }) => {
    const supabase = context.supabase as SB;
    await assertMember(supabase, context.userId, data.organizationId);
    const rows = data.postIds.map((postId) => ({
      organization_id: data.organizationId,
      site_id: data.siteId,
      playbook_id: data.playbookId,
      post_id: postId,
      status: "queued",
      created_by: context.userId,
    }));
    const { data: inserted, error } = await supabase
      .from("playbook_runs")
      .insert(rows)
      .select("id");
    if (error) throw error;
    // Enqueue background jobs to materialize the diff + WP write
    const jobs = (inserted ?? []).map((r: { id: string }) => ({
      organization_id: data.organizationId,
      site_id: data.siteId,
      created_by: context.userId,
      job_type: "playbook.apply",
      payload: { run_id: r.id, playbook_id: data.playbookId },
      status: "queued",
    }));
    if (jobs.length) await supabase.from("background_jobs").insert(jobs);
    return { queued: rows.length };
  });

export const listPlaybookRuns = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((i) =>
    orgScoped.extend({ limit: z.number().int().min(1).max(200).default(50) }).parse(i),
  )
  .handler(async ({ data, context }) => {
    const supabase = context.supabase as SB;
    await assertMember(supabase, context.userId, data.organizationId);
    const { data: rows, error } = await supabase
      .from("playbook_runs")
      .select("id, playbook_id, post_id, status, error, created_at, applied_changeset_id")
      .eq("organization_id", data.organizationId)
      .order("created_at", { ascending: false })
      .limit(data.limit);
    if (error) throw error;
    return { runs: rows ?? [] };
  });

export const listChangesets = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((i) =>
    orgScoped.extend({ limit: z.number().int().min(1).max(200).default(50) }).parse(i),
  )
  .handler(async ({ data, context }) => {
    const supabase = context.supabase as SB;
    await assertMember(supabase, context.userId, data.organizationId);
    const { data: rows, error } = await supabase
      .from("content_changesets")
      .select("id, post_id, wp_post_id, source, playbook_id, asset_blocks_added, applied_at")
      .eq("organization_id", data.organizationId)
      .order("applied_at", { ascending: false })
      .limit(data.limit);
    if (error) throw error;
    return { changesets: rows ?? [] };
  });

/**
 * Compute 7/14/28-day GSC clicks/impressions/position deltas for a changeset.
 * Baseline = same window length BEFORE applied_at. Post = same window AFTER.
 * Idempotent via UNIQUE(changeset_id, window_days).
 */
export const measureLift = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((i) =>
    orgScoped.extend({ changesetId: z.string().uuid() }).parse(i),
  )
  .handler(async ({ data, context }) => {
    const supabase = context.supabase as SB;
    await assertMember(supabase, context.userId, data.organizationId);
    const { data: cs, error: csErr } = await supabase
      .from("content_changesets")
      .select("id, site_id, post_id, wp_post_id, applied_at, organization_id")
      .eq("id", data.changesetId)
      .eq("organization_id", data.organizationId)
      .single();
    if (csErr || !cs) throw new Error("Changeset not found");

    // Resolve URL from wordpress_posts if available
    let url: string | null = null;
    if (cs.post_id) {
      const { data: post } = await supabase
        .from("wordpress_posts")
        .select("url")
        .eq("id", cs.post_id)
        .maybeSingle();
      url = post?.url ?? null;
    }
    if (!url) return { measured: 0, note: "no URL on changeset" };

    const appliedAt = new Date(cs.applied_at);
    const results: Array<{ window_days: number }> = [];
    for (const win of [7, 14, 28]) {
      const baselineStart = new Date(appliedAt.getTime() - win * 86400000);
      const postEnd = new Date(appliedAt.getTime() + win * 86400000);
      const { data: rows } = await supabase
        .from("search_console_daily")
        .select("date, clicks, impressions, position")
        .eq("organization_id", data.organizationId)
        .eq("site_id", cs.site_id)
        .eq("page", url)
        .gte("date", baselineStart.toISOString().slice(0, 10))
        .lte("date", postEnd.toISOString().slice(0, 10));
      if (!rows || rows.length === 0) continue;
      let bC = 0, bI = 0, bPsum = 0, bPn = 0;
      let pC = 0, pI = 0, pPsum = 0, pPn = 0;
      for (const r of rows as Array<{
        date: string;
        clicks: number;
        impressions: number;
        position: number | null;
      }>) {
        const d = new Date(r.date);
        if (d < appliedAt) {
          bC += r.clicks; bI += r.impressions;
          if (r.position != null) { bPsum += Number(r.position); bPn++; }
        } else {
          pC += r.clicks; pI += r.impressions;
          if (r.position != null) { pPsum += Number(r.position); pPn++; }
        }
      }
      const bP = bPn ? bPsum / bPn : null;
      const pP = pPn ? pPsum / pPn : null;
      await supabase
        .from("lift_measurements")
        .upsert(
          {
            organization_id: data.organizationId,
            site_id: cs.site_id,
            changeset_id: cs.id,
            window_days: win,
            baseline_clicks: bC,
            baseline_impressions: bI,
            baseline_position: bP,
            post_clicks: pC,
            post_impressions: pI,
            post_position: pP,
            clicks_delta: pC - bC,
            impressions_delta: pI - bI,
            position_delta: bP != null && pP != null ? bP - pP : null,
          },
          { onConflict: "changeset_id,window_days" },
        );
      results.push({ window_days: win });
    }
    return { measured: results.length };
  });

export const listLiftSummary = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((i) => orgScoped.parse(i))
  .handler(async ({ data, context }) => {
    const supabase = context.supabase as SB;
    await assertMember(supabase, context.userId, data.organizationId);
    const { data: rows, error } = await supabase
      .from("lift_measurements")
      .select("changeset_id, window_days, clicks_delta, impressions_delta, position_delta")
      .eq("organization_id", data.organizationId)
      .order("measured_at", { ascending: false })
      .limit(500);
    if (error) throw error;
    return { measurements: rows ?? [] };
  });