/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVitalsRouteImport } from './routes/_authenticated/vitals'
import { Route as AuthenticatedTopicalMapsRouteImport } from './routes/_authenticated/topical-maps'
import { Route as AuthenticatedTechnicalRouteImport } from './routes/_authenticated/technical'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedSitesRouteImport } from './routes/_authenticated/sites'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRolloutsRouteImport } from './routes/_authenticated/rollouts'
import { Route as AuthenticatedRecommendationsRouteImport } from './routes/_authenticated/recommendations'
import { Route as AuthenticatedPlaybooksRouteImport } from './routes/_authenticated/playbooks'
import { Route as AuthenticatedOptimizationRouteImport } from './routes/_authenticated/optimization'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedObservabilityRouteImport } from './routes/_authenticated/observability'
import { Route as AuthenticatedLiftRouteImport } from './routes/_authenticated/lift'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated/integrations'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContentInventoryRouteImport } from './routes/_authenticated/content-inventory'
import { Route as AuthenticatedBriefsRouteImport } from './routes/_authenticated/briefs'
import { Route as AuthenticatedAuditsRouteImport } from './routes/_authenticated/audits'
import { Route as AuthenticatedAuditLogsRouteImport } from './routes/_authenticated/audit-logs'
import { Route as AuthenticatedApprovalsRouteImport } from './routes/_authenticated/approvals'
import { Route as AuthenticatedAiVisibilityRouteImport } from './routes/_authenticated/ai-visibility'
import { Route as ApiPublicErrorsRouteImport } from './routes/api/public/errors'
import { Route as ApiPublicCronWorkerRouteImport } from './routes/api/public/cron/worker'
import { Route as ApiPublicCronScanRouteImport } from './routes/api/public/cron/scan'
import { Route as ApiPublicCronGscPullRouteImport } from './routes/api/public/cron/gsc-pull'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVitalsRoute = AuthenticatedVitalsRouteImport.update({
  id: '/vitals',
  path: '/vitals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTopicalMapsRoute =
  AuthenticatedTopicalMapsRouteImport.update({
    id: '/topical-maps',
    path: '/topical-maps',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTechnicalRoute = AuthenticatedTechnicalRouteImport.update({
  id: '/technical',
  path: '/technical',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSitesRoute = AuthenticatedSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRolloutsRoute = AuthenticatedRolloutsRouteImport.update({
  id: '/rollouts',
  path: '/rollouts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecommendationsRoute =
  AuthenticatedRecommendationsRouteImport.update({
    id: '/recommendations',
    path: '/recommendations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlaybooksRoute = AuthenticatedPlaybooksRouteImport.update({
  id: '/playbooks',
  path: '/playbooks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOptimizationRoute =
  AuthenticatedOptimizationRouteImport.update({
    id: '/optimization',
    path: '/optimization',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedObservabilityRoute =
  AuthenticatedObservabilityRouteImport.update({
    id: '/observability',
    path: '/observability',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLiftRoute = AuthenticatedLiftRouteImport.update({
  id: '/lift',
  path: '/lift',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContentInventoryRoute =
  AuthenticatedContentInventoryRouteImport.update({
    id: '/content-inventory',
    path: '/content-inventory',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBriefsRoute = AuthenticatedBriefsRouteImport.update({
  id: '/briefs',
  path: '/briefs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditsRoute = AuthenticatedAuditsRouteImport.update({
  id: '/audits',
  path: '/audits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditLogsRoute = AuthenticatedAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApprovalsRoute = AuthenticatedApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiVisibilityRoute =
  AuthenticatedAiVisibilityRouteImport.update({
    id: '/ai-visibility',
    path: '/ai-visibility',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicErrorsRoute = ApiPublicErrorsRouteImport.update({
  id: '/api/public/errors',
  path: '/api/public/errors',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronWorkerRoute = ApiPublicCronWorkerRouteImport.update({
  id: '/api/public/cron/worker',
  path: '/api/public/cron/worker',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronScanRoute = ApiPublicCronScanRouteImport.update({
  id: '/api/public/cron/scan',
  path: '/api/public/cron/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronGscPullRoute = ApiPublicCronGscPullRouteImport.update({
  id: '/api/public/cron/gsc-pull',
  path: '/api/public/cron/gsc-pull',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/ai-visibility': typeof AuthenticatedAiVisibilityRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/audits': typeof AuthenticatedAuditsRoute
  '/briefs': typeof AuthenticatedBriefsRoute
  '/content-inventory': typeof AuthenticatedContentInventoryRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/lift': typeof AuthenticatedLiftRoute
  '/observability': typeof AuthenticatedObservabilityRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/optimization': typeof AuthenticatedOptimizationRoute
  '/playbooks': typeof AuthenticatedPlaybooksRoute
  '/recommendations': typeof AuthenticatedRecommendationsRoute
  '/rollouts': typeof AuthenticatedRolloutsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sites': typeof AuthenticatedSitesRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/technical': typeof AuthenticatedTechnicalRoute
  '/topical-maps': typeof AuthenticatedTopicalMapsRoute
  '/vitals': typeof AuthenticatedVitalsRoute
  '/api/public/errors': typeof ApiPublicErrorsRoute
  '/api/public/cron/gsc-pull': typeof ApiPublicCronGscPullRoute
  '/api/public/cron/scan': typeof ApiPublicCronScanRoute
  '/api/public/cron/worker': typeof ApiPublicCronWorkerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/ai-visibility': typeof AuthenticatedAiVisibilityRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/audits': typeof AuthenticatedAuditsRoute
  '/briefs': typeof AuthenticatedBriefsRoute
  '/content-inventory': typeof AuthenticatedContentInventoryRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/lift': typeof AuthenticatedLiftRoute
  '/observability': typeof AuthenticatedObservabilityRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/optimization': typeof AuthenticatedOptimizationRoute
  '/playbooks': typeof AuthenticatedPlaybooksRoute
  '/recommendations': typeof AuthenticatedRecommendationsRoute
  '/rollouts': typeof AuthenticatedRolloutsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sites': typeof AuthenticatedSitesRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/technical': typeof AuthenticatedTechnicalRoute
  '/topical-maps': typeof AuthenticatedTopicalMapsRoute
  '/vitals': typeof AuthenticatedVitalsRoute
  '/api/public/errors': typeof ApiPublicErrorsRoute
  '/api/public/cron/gsc-pull': typeof ApiPublicCronGscPullRoute
  '/api/public/cron/scan': typeof ApiPublicCronScanRoute
  '/api/public/cron/worker': typeof ApiPublicCronWorkerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/ai-visibility': typeof AuthenticatedAiVisibilityRoute
  '/_authenticated/approvals': typeof AuthenticatedApprovalsRoute
  '/_authenticated/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/_authenticated/audits': typeof AuthenticatedAuditsRoute
  '/_authenticated/briefs': typeof AuthenticatedBriefsRoute
  '/_authenticated/content-inventory': typeof AuthenticatedContentInventoryRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/lift': typeof AuthenticatedLiftRoute
  '/_authenticated/observability': typeof AuthenticatedObservabilityRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/optimization': typeof AuthenticatedOptimizationRoute
  '/_authenticated/playbooks': typeof AuthenticatedPlaybooksRoute
  '/_authenticated/recommendations': typeof AuthenticatedRecommendationsRoute
  '/_authenticated/rollouts': typeof AuthenticatedRolloutsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/sites': typeof AuthenticatedSitesRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/technical': typeof AuthenticatedTechnicalRoute
  '/_authenticated/topical-maps': typeof AuthenticatedTopicalMapsRoute
  '/_authenticated/vitals': typeof AuthenticatedVitalsRoute
  '/api/public/errors': typeof ApiPublicErrorsRoute
  '/api/public/cron/gsc-pull': typeof ApiPublicCronGscPullRoute
  '/api/public/cron/scan': typeof ApiPublicCronScanRoute
  '/api/public/cron/worker': typeof ApiPublicCronWorkerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/ai-visibility'
    | '/approvals'
    | '/audit-logs'
    | '/audits'
    | '/briefs'
    | '/content-inventory'
    | '/dashboard'
    | '/integrations'
    | '/lift'
    | '/observability'
    | '/onboarding'
    | '/optimization'
    | '/playbooks'
    | '/recommendations'
    | '/rollouts'
    | '/settings'
    | '/sites'
    | '/tasks'
    | '/technical'
    | '/topical-maps'
    | '/vitals'
    | '/api/public/errors'
    | '/api/public/cron/gsc-pull'
    | '/api/public/cron/scan'
    | '/api/public/cron/worker'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/ai-visibility'
    | '/approvals'
    | '/audit-logs'
    | '/audits'
    | '/briefs'
    | '/content-inventory'
    | '/dashboard'
    | '/integrations'
    | '/lift'
    | '/observability'
    | '/onboarding'
    | '/optimization'
    | '/playbooks'
    | '/recommendations'
    | '/rollouts'
    | '/settings'
    | '/sites'
    | '/tasks'
    | '/technical'
    | '/topical-maps'
    | '/vitals'
    | '/api/public/errors'
    | '/api/public/cron/gsc-pull'
    | '/api/public/cron/scan'
    | '/api/public/cron/worker'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/ai-visibility'
    | '/_authenticated/approvals'
    | '/_authenticated/audit-logs'
    | '/_authenticated/audits'
    | '/_authenticated/briefs'
    | '/_authenticated/content-inventory'
    | '/_authenticated/dashboard'
    | '/_authenticated/integrations'
    | '/_authenticated/lift'
    | '/_authenticated/observability'
    | '/_authenticated/onboarding'
    | '/_authenticated/optimization'
    | '/_authenticated/playbooks'
    | '/_authenticated/recommendations'
    | '/_authenticated/rollouts'
    | '/_authenticated/settings'
    | '/_authenticated/sites'
    | '/_authenticated/tasks'
    | '/_authenticated/technical'
    | '/_authenticated/topical-maps'
    | '/_authenticated/vitals'
    | '/api/public/errors'
    | '/api/public/cron/gsc-pull'
    | '/api/public/cron/scan'
    | '/api/public/cron/worker'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiPublicErrorsRoute: typeof ApiPublicErrorsRoute
  ApiPublicCronGscPullRoute: typeof ApiPublicCronGscPullRoute
  ApiPublicCronScanRoute: typeof ApiPublicCronScanRoute
  ApiPublicCronWorkerRoute: typeof ApiPublicCronWorkerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vitals': {
      id: '/_authenticated/vitals'
      path: '/vitals'
      fullPath: '/vitals'
      preLoaderRoute: typeof AuthenticatedVitalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/topical-maps': {
      id: '/_authenticated/topical-maps'
      path: '/topical-maps'
      fullPath: '/topical-maps'
      preLoaderRoute: typeof AuthenticatedTopicalMapsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/technical': {
      id: '/_authenticated/technical'
      path: '/technical'
      fullPath: '/technical'
      preLoaderRoute: typeof AuthenticatedTechnicalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sites': {
      id: '/_authenticated/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof AuthenticatedSitesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rollouts': {
      id: '/_authenticated/rollouts'
      path: '/rollouts'
      fullPath: '/rollouts'
      preLoaderRoute: typeof AuthenticatedRolloutsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recommendations': {
      id: '/_authenticated/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof AuthenticatedRecommendationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/playbooks': {
      id: '/_authenticated/playbooks'
      path: '/playbooks'
      fullPath: '/playbooks'
      preLoaderRoute: typeof AuthenticatedPlaybooksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/optimization': {
      id: '/_authenticated/optimization'
      path: '/optimization'
      fullPath: '/optimization'
      preLoaderRoute: typeof AuthenticatedOptimizationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/observability': {
      id: '/_authenticated/observability'
      path: '/observability'
      fullPath: '/observability'
      preLoaderRoute: typeof AuthenticatedObservabilityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lift': {
      id: '/_authenticated/lift'
      path: '/lift'
      fullPath: '/lift'
      preLoaderRoute: typeof AuthenticatedLiftRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/content-inventory': {
      id: '/_authenticated/content-inventory'
      path: '/content-inventory'
      fullPath: '/content-inventory'
      preLoaderRoute: typeof AuthenticatedContentInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/briefs': {
      id: '/_authenticated/briefs'
      path: '/briefs'
      fullPath: '/briefs'
      preLoaderRoute: typeof AuthenticatedBriefsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audits': {
      id: '/_authenticated/audits'
      path: '/audits'
      fullPath: '/audits'
      preLoaderRoute: typeof AuthenticatedAuditsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit-logs': {
      id: '/_authenticated/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuthenticatedAuditLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/approvals': {
      id: '/_authenticated/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthenticatedApprovalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-visibility': {
      id: '/_authenticated/ai-visibility'
      path: '/ai-visibility'
      fullPath: '/ai-visibility'
      preLoaderRoute: typeof AuthenticatedAiVisibilityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/errors': {
      id: '/api/public/errors'
      path: '/api/public/errors'
      fullPath: '/api/public/errors'
      preLoaderRoute: typeof ApiPublicErrorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/worker': {
      id: '/api/public/cron/worker'
      path: '/api/public/cron/worker'
      fullPath: '/api/public/cron/worker'
      preLoaderRoute: typeof ApiPublicCronWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/scan': {
      id: '/api/public/cron/scan'
      path: '/api/public/cron/scan'
      fullPath: '/api/public/cron/scan'
      preLoaderRoute: typeof ApiPublicCronScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/gsc-pull': {
      id: '/api/public/cron/gsc-pull'
      path: '/api/public/cron/gsc-pull'
      fullPath: '/api/public/cron/gsc-pull'
      preLoaderRoute: typeof ApiPublicCronGscPullRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiVisibilityRoute: typeof AuthenticatedAiVisibilityRoute
  AuthenticatedApprovalsRoute: typeof AuthenticatedApprovalsRoute
  AuthenticatedAuditLogsRoute: typeof AuthenticatedAuditLogsRoute
  AuthenticatedAuditsRoute: typeof AuthenticatedAuditsRoute
  AuthenticatedBriefsRoute: typeof AuthenticatedBriefsRoute
  AuthenticatedContentInventoryRoute: typeof AuthenticatedContentInventoryRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedLiftRoute: typeof AuthenticatedLiftRoute
  AuthenticatedObservabilityRoute: typeof AuthenticatedObservabilityRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedOptimizationRoute: typeof AuthenticatedOptimizationRoute
  AuthenticatedPlaybooksRoute: typeof AuthenticatedPlaybooksRoute
  AuthenticatedRecommendationsRoute: typeof AuthenticatedRecommendationsRoute
  AuthenticatedRolloutsRoute: typeof AuthenticatedRolloutsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSitesRoute: typeof AuthenticatedSitesRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedTechnicalRoute: typeof AuthenticatedTechnicalRoute
  AuthenticatedTopicalMapsRoute: typeof AuthenticatedTopicalMapsRoute
  AuthenticatedVitalsRoute: typeof AuthenticatedVitalsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiVisibilityRoute: AuthenticatedAiVisibilityRoute,
  AuthenticatedApprovalsRoute: AuthenticatedApprovalsRoute,
  AuthenticatedAuditLogsRoute: AuthenticatedAuditLogsRoute,
  AuthenticatedAuditsRoute: AuthenticatedAuditsRoute,
  AuthenticatedBriefsRoute: AuthenticatedBriefsRoute,
  AuthenticatedContentInventoryRoute: AuthenticatedContentInventoryRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedLiftRoute: AuthenticatedLiftRoute,
  AuthenticatedObservabilityRoute: AuthenticatedObservabilityRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedOptimizationRoute: AuthenticatedOptimizationRoute,
  AuthenticatedPlaybooksRoute: AuthenticatedPlaybooksRoute,
  AuthenticatedRecommendationsRoute: AuthenticatedRecommendationsRoute,
  AuthenticatedRolloutsRoute: AuthenticatedRolloutsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSitesRoute: AuthenticatedSitesRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedTechnicalRoute: AuthenticatedTechnicalRoute,
  AuthenticatedTopicalMapsRoute: AuthenticatedTopicalMapsRoute,
  AuthenticatedVitalsRoute: AuthenticatedVitalsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiPublicErrorsRoute: ApiPublicErrorsRoute,
  ApiPublicCronGscPullRoute: ApiPublicCronGscPullRoute,
  ApiPublicCronScanRoute: ApiPublicCronScanRoute,
  ApiPublicCronWorkerRoute: ApiPublicCronWorkerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
